# sui-client-gen
# https://github.com/kunalabs-io/sui-client-gen

[config]
# will be set to mainnet by default if omitted
rpc = "https://fullnode.mainnet.sui.io:443"

[packages]
# based on source code (syntax same as in Move.toml):
Memechan = { local = "../memechan" }
