[package]
name = "Memechan"
version = "0.0.1"
edition = "legacy"
published-at = "0xe1d2d1f39e6f8bf70767d24dffaf11e16e6eef0fac03dabc8d2f650874d2084f"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.22.0" }
# SuiTears = { git = "https://github.com/interest-protocol/suitears.git", subdir = "contracts", rev = "mainnet-1.0.0-beta" }
# CLAMM = { git = "https://github.com/interest-protocol/clamm.git", subdir = "contracts", rev = "mainnet/1.1.1-alpha" }

SuiTears = { local = "../interest/suitears" }
CLAMM = { local = "../interest/clamm" }

[addresses]
memechan = "0xe1d2d1f39e6f8bf70767d24dffaf11e16e6eef0fac03dabc8d2f650874d2084f"
