[package]
name = "Memechan"
version = "0.0.1"
edition = "legacy"
published-at = "0x01b0ce8c624d17de61440d13a263527b2fd5b5a5d4b6aac286d88755125b1b32"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.22.0" }
# SuiTears = { git = "https://github.com/interest-protocol/suitears.git", subdir = "contracts", rev = "mainnet-1.0.0-beta" }
# CLAMM = { git = "https://github.com/interest-protocol/clamm.git", subdir = "contracts", rev = "mainnet/1.1.1-alpha" }

SuiTears = { local = "../interest/suitears" }
CLAMM = { local = "../interest/clamm" }

[addresses]
memechan = "0x01b0ce8c624d17de61440d13a263527b2fd5b5a5d4b6aac286d88755125b1b32"
